### ISSUE TITLE
NullPointerException when running logging enabled

### ISSUE THREAD

**Issue by chbndrhnns** [plantuml/plantuml-server#111]
I receive the error shown below when I run the Jetty-based server in Docker with `-e PLANTUML_STATS=true`:

```
2019-08-01 11:08:22.869:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@5e5792a0{plantuml,/,[file:///tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-6842626921359374868.dir/webapp/, jar:file:///tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-6842626921359374868.dir/webapp/WEB-INF/lib/codemirror-3.21.jar!/META-INF/resources],AVAILABLE}{/ROOT.war}
2019-08-01 11:08:22.885:INFO:oejs.AbstractConnector:main: Started ServerConnector@2145b572{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-08-01 11:08:22.885:INFO:oejs.Server:main: Started @1635ms
Aug 01, 2019 11:09:03 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: Couldn't create user preferences directory. User preferences are unusable.
Aug 01, 2019 11:09:03 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: No such file or directory
SPECIAL TRACE FOR PLANTUML: Could not lock User prefs.  Unix error code 2.
Error reloading stats java.util.prefs.BackingStoreException: Couldn't get file lock.
2019-08-01 11:09:05.542:WARN:oejs.HttpChannel:qtp1343441044-18: /uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
java.lang.NullPointerException
	at net.sourceforge.plantuml.stats.StatsUtilsIncrement.onceMoreParse(StatsUtilsIncrement.java:67)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:136)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:155)
	at net.sourceforge.plantuml.api.PlantumlUtils.hasCMapData(PlantumlUtils.java:56)
	at net.sourceforge.plantuml.servlet.PlantUmlServlet.doGet(PlantUmlServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```

It works fine without that option.

**Comment by arnaudroques** [comment]
The important trace is:
```
WARNING: Couldn't create user preferences directory. User preferences are unusable.
Aug 01, 2019 11:09:03 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: No such file or directory
SPECIAL TRACE FOR PLANTUML: Could not lock User prefs.  Unix error code 2.
Error reloading stats java.util.prefs.BackingStoreException: Couldn't get file lock.
```
It looks like the JVM cannot create user preference directory.
Probably some file system access...

**Comment by chbndrhnns** [comment]
Do you know what kind of file system access is required for running plantuml with that option?

**Comment by McFoggy** [comment]
The base jetty image is lacking permissions to use the default implementation of `java.util.Preferences` which is required (at least the user node) by plantuml itself.

If you provide explicitly to the JVM writable directories for the preferences, then it works
```
$ docker run --rm -it -p 8080:8080 plantuml/plantuml-server:jetty /bin/bash

$ mkdir -p /tmp/jetty/.java/.systemPrefs
$ mkdir -p /tmp/jetty/.java/.userPrefs
$ PLANTUML_STATS=true java -Djava.util.prefs.systemRoot=/tmp/jetty -Djava.util.prefs.userRoot=/tmp/jetty -jar /usr/local/jetty/start.jar
```
