### ISSUE TITLE
!includeurl doesn't work with HTTPS, e.g. Github

### ISSUE THREAD

**Issue by KMax** [plantuml/plantuml-server#133]
Running PlantUML Server locally with `mvn jetty:run` from tag `v1.2020.0` and using examples from https://github.com/RicardoNiepel/C4-PlantUML.

Particullary this one doesn't work:
```
@startuml Basic Sample
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

Person(admin, "Administrator")
System_Boundary(c1, "Sample System") {
    Container(web_app, "Web Application", "C#, ASP.NET Core 2.1 MVC", "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")

Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")
@enduml
```

Message from the preview in the Visual Code: `Cannon open URL`. I use the [PlantUML](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml) plugin.

The exception from the server:
```
javax.net.ssl.SSLException: Connection reset
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:171)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at java.base/java.net.URL.openStream(URL.java:1162)
        at net.sourceforge.plantuml.preproc2.PreprocessorUtils.getReaderIncludeUrl2(PreprocessorUtils.java:122)
        at net.sourceforge.plantuml.tim.TContext.executeInclude(TContext.java:669)
        at net.sourceforge.plantuml.tim.TContext.executeOneLine(TContext.java:300)
        at net.sourceforge.plantuml.tim.TimLoader.load(TimLoader.java:65)
        at net.sourceforge.plantuml.BlockUml.<init>(BlockUml.java:114)
        at net.sourceforge.plantuml.BlockUmlBuilder.init(BlockUmlBuilder.java:123)
        at net.sourceforge.plantuml.BlockUmlBuilder.<init>(BlockUmlBuilder.java:74)
        at net.sourceforge.plantuml.SourceStringReader.<init>(SourceStringReader.java:89)
        at net.sourceforge.plantuml.SourceStringReader.<init>(SourceStringReader.java:82)
        at net.sourceforge.plantuml.SourceStringReader.<init>(SourceStringReader.java:70)
        at net.sourceforge.plantuml.SourceStringReader.<init>(SourceStringReader.java:62)
        at net.sourceforge.plantuml.servlet.DiagramResponse.sendDiagram(DiagramResponse.java:89)
        at net.sourceforge.plantuml.servlet.UmlDiagramService.doDiagramResponse(UmlDiagramService.java:101)
        at net.sourceforge.plantuml.servlet.UmlDiagramService.doPost(UmlDiagramService.java:88)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:754)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:558)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:488)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:520)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:973)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:417)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:907)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
        at org.eclipse.jetty.server.Server.handle(Server.java:346)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:442)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:941)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:893)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
        at java.base/java.lang.Thread.run(Thread.java:830)
        Suppressed: java.net.SocketException: Connection reset by peer
                at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:421)
                at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:441)
                at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:825)
                at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1007)
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:82)
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:355)
                ... 52 more
Caused by: java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:324)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:937)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:450)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        ... 49 more
```

**Comment by 3kami3** [comment]
I checked it again.

### **Environment**
Amazon EC2 instance
Ubuntu Server 20.04 LTS (HVM), SSD Volume Type - ami-0aa7c595324d25274 (64 bit x86)

### **Build and run procedure**
```
$ sudo apt-get update
$ sudo apt-get -y install openjdk-14-jdk maven graphviz
$ sudo apt-get -y install git

$ git clone https://github.com/plantuml/plantuml-server.git
$ cd plantuml-server
$ mvn jetty:run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...

<snip>

[INFO] Configuring Jetty for project: PlantUML Servlet
[INFO] webAppSourceDirectory /home/ubuntu/plantuml-server/src/main/webapp does not exist. Defaulting to /home/ubuntu/plantuml-server/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /home/ubuntu/plantuml-server/target/classes
[INFO] Context path = /plantuml
[INFO] Tmp directory = /home/ubuntu/plantuml-server/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:/home/ubuntu/plantuml-server/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /home/ubuntu/plantuml-server/src/main/webapp
2020-06-25 12:26:06.320:INFO:oejs.Server:jetty-8.0.4.v20111024
2020-06-25 12:26:06.951:INFO:oejpw.PlusConfiguration:No Transaction manager found - if your webapp requires one, please configure one.
2020-06-25 12:26:09.266:INFO:oejsh.ContextHandler:started o.m.j.p.JettyWebAppContext{/plantuml,[file:/home/ubuntu/plantuml-server/src/main/webapp/, jar:file:/home/ubuntu/.m2/repository/org/webjars/codemirror/3.21/codemirror-3.21.jar!/META-INF/resources/]},file:/home/ubuntu/plantuml-server/src/main/webapp/
2020-06-25 12:26:09.275:INFO:oejsh.ContextHandler:started o.m.j.p.JettyWebAppContext{/plantuml,[file:/home/ubuntu/plantuml-server/src/main/webapp/, jar:file:/home/ubuntu/.m2/repository/org/webjars/codemirror/3.21/codemirror-3.21.jar!/META-INF/resources/]},file:/home/ubuntu/plantuml-server/src/main/webapp/
2020-06-25 12:26:09.277:INFO:oejsh.ContextHandler:started o.m.j.p.JettyWebAppContext{/plantuml,[file:/home/ubuntu/plantuml-server/src/main/webapp/, jar:file:/home/ubuntu/.m2/repository/org/webjars/codemirror/3.21/codemirror-3.21.jar!/META-INF/resources/]},file:/home/ubuntu/plantuml-server/src/main/webapp/
2020-06-25 12:26:09.362:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080 STARTING
[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 5 seconds.
```

### **Result**
no problems.
<img width="741" alt="plantuml_s" src="https://user-images.githubusercontent.com/12627100/85724875-95099300-b72f-11ea-9ee8-24f37a211d42.png">

---

What is your OS environment?
Do you have the necessary CA root certificates installed on your Java environment keystores?
```
$ keytool -list -v -storepass changeit -keystore /usr/lib/jvm/java-1.14.0-openjdk-amd64/lib/security/cacerts
Warning: use -cacerts option to access cacerts keystore
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 127 entries

<cut>
```

**Comment by KMax** [comment]
I'm sorry. I'm not using the server anymore, so I can't verify. I switched to Intellij IDEA which has a plugin for PlantUML, so I don't need to use the server anymore. I think, the issue can be closed at least for now.
