### ISSUE TITLE
error in version 1.2020.7

### ISSUE THREAD

**Issue by MarcoSchaar** [plantuml/plantuml-server#142]
Hi 
while testing ...

Request that failed: /uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
Status code: 500
Exception: java.lang.NullPointerException: while trying to invoke the method net.sourceforge.plantuml.stats.ParsedGenerated.parsed() of a null object loaded from static field net.sourceforge.plantuml.stats.StatsUtils.fullEver

1.2020.6 works in same environment

**Comment by arnaudroques** [comment]
Weird : this has not changed.
Nothing is working ?

Do you have any stacktrace ? It would help us to understand what's going on.

**Comment by MarcoSchaar** [comment]
Hi 
hope this could help

SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [plantumlservlet] in context with path [] threw exception
        java.lang.NullPointerException: while trying to invoke the method net.sourceforge.plantuml.stats.ParsedGenerated.parsed() of a 
null object loaded from static field net.sourceforge.plantuml.stats.StatsUtils.fullEver
                at net.sourceforge.plantuml.stats.StatsUtilsIncrement.onceMoreParse(StatsUtilsIncrement.java:67)
                at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:140)
                at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:161)
                at net.sourceforge.plantuml.api.PlantumlUtils.hasCMapData(PlantumlUtils.java:56)
                at net.sourceforge.plantuml.servlet.PlantUmlServlet.doGet(PlantUmlServlet.java:112)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:836)

**Comment by arnaudroques** [comment]
Did you use statistics ? (see https://plantuml.com/en/statistics-report )
Anyway, we fix something in last beta http://beta.plantuml.net/plantuml.war
Tell us if it helps !

**Comment by MarcoSchaar** [comment]
yes indeed, PLANTUML_STATS is set to true but found no way to get statistics via web ui

successfully tested version 8 beta
