### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot decode webjars/codemirror/3.21/lib/codemirror.js

### ISSUE THREAD

**Issue by Beelal** [plantuml/plantuml-server#24]
The server is running on AWS with mvn jetty:run command:

java.lang.IllegalArgumentException: Cannot decode webjars/codemirror/3.21/lib/codemirror.js
    at net.sourceforge.plantuml.code.AsciiEncoder.decode(AsciiEncoder.java:62)
    at net.sourceforge.plantuml.code.TranscoderImpl.decode(TranscoderImpl.java:69)
    at net.sourceforge.plantuml.code.TranscoderSmart.decode(TranscoderSmart.java:48)
    at net.sourceforge.plantuml.servlet.PlantUmlServlet.getTextFromUrl(PlantUmlServlet.java:138)
    at net.sourceforge.plantuml.servlet.PlantUmlServlet.doGet(PlantUmlServlet.java:89)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:558)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:488)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:520)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:973)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:417)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:907)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
    at org.eclipse.jetty.server.Server.handle(Server.java:346)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:442)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)

**Comment by maximesinclair** [comment]
Hi Beelal
Could you please give a little more information about this stack trace ? Does it occur at the server startup ? Could you visit the index page of the server ?

**Comment by Beelal** [comment]
Sorry for the late reply:

Here is what I did:

1. Downloaded and unzip the code.
2. export GRAPHVIZ_DOT=/opt/local/bin/dot
3. mvn jetty:run

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building PlantUML Servlet 1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:8.0.4.v20111024:run (default-cli) > test-compile @ plantumlservlet >>>
Downloading: https://repo.maven.apache.org/maven2/net/sourceforge/plantuml/plantuml/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/net/sourceforge/plantuml/plantuml/maven-metadata.xml (5 KB at 3.6 KB/sec)
[INFO]
[INFO] --- maven-checkstyle-plugin:2.11:check (validate) @ plantumlservlet ---
[INFO] Starting audit...
Audit done.

[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ plantumlservlet ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ plantumlservlet ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ plantumlservlet ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/bee/Bilsoft/projects/uml/plantuml-server/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ plantumlservlet ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< jetty-maven-plugin:8.0.4.v20111024:run (default-cli) < test-compile @ plantumlservlet <<<
[INFO]
[INFO] --- jetty-maven-plugin:8.0.4.v20111024:run (default-cli) @ plantumlservlet ---
[INFO] Configuring Jetty for project: PlantUML Servlet
[INFO] webAppSourceDirectory /Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp does not exist. Defaulting to /Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /Users/bee/Bilsoft/projects/uml/plantuml-server/target/classes
[INFO] Context path = /plantuml
[INFO] Tmp directory = /Users/bee/Bilsoft/projects/uml/plantuml-server/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:/Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp
2016-06-29 12:20:42.513:INFO:oejs.Server:jetty-8.0.4.v20111024
2016-06-29 12:20:42.867:INFO:oejpw.PlusConfiguration:No Transaction manager found - if your webapp requires one, please configure one.
2016-06-29 12:20:44.064:INFO:oejsh.ContextHandler:started o.m.j.p.JettyWebAppContext{/plantuml,[file:/Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp/, jar:file:/Users/bee/.m2/repository/org/webjars/codemirror/3.21/codemirror-3.21.jar!/META-INF/resources/]},file:/Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp/
2016-06-29 12:20:44.065:INFO:oejsh.ContextHandler:started o.m.j.p.JettyWebAppContext{/plantuml,[file:/Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp/, jar:file:/Users/bee/.m2/repository/org/webjars/codemirror/3.21/codemirror-3.21.jar!/META-INF/resources/]},file:/Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp/
2016-06-29 12:20:44.065:INFO:oejsh.ContextHandler:started o.m.j.p.JettyWebAppContext{/plantuml,[file:/Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp/, jar:file:/Users/bee/.m2/repository/org/webjars/codemirror/3.21/codemirror-3.21.jar!/META-INF/resources/]},file:/Users/bee/Bilsoft/projects/uml/plantuml-server/src/main/webapp/
2016-06-29 12:20:44.137:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080 STARTING
[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 5 seconds.

4. Visited page http://localhost:8080/plantuml. Page showed up fine but on the console I got:

java.lang.IllegalArgumentException: Cannot decode webjars/codemirror/3.21/lib/codemirror.css
	at net.sourceforge.plantuml.code.AsciiEncoder.decode(AsciiEncoder.java:62)
	at net.sourceforge.plantuml.code.TranscoderImpl.decode(TranscoderImpl.java:69)
	at net.sourceforge.plantuml.code.TranscoderSmart.decode(TranscoderSmart.java:48)
	at net.sourceforge.plantuml.servlet.PlantUmlServlet.getTextFromUrl(PlantUmlServlet.java:138)
	at net.sourceforge.plantuml.servlet.PlantUmlServlet.doGet(PlantUmlServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:558)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:488)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:520)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:973)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:417)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:907)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:346)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:442)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Thread.java:745)

**Comment by 0wnrepo** [comment]
I also have this issue, on os x yosemite.

**Comment by maximesinclair** [comment]
I don't know why webjars (http://www.webjars.org/) is not well supported in this configuration.
If someone can help to investigate this case.

Hopefully, the codemirror editor is not mandatory so you still can use the server.

**Comment by je2ryw** [comment]
please see the pull request #28
