### ISSUE TITLE
Compile error when running with Java 10

### ISSUE THREAD

**Issue by tnguyen14** [plantuml/plantuml-server#76]
I am running this locally on my mac with Java 10, and the server started fine, but on first request, I am getting the following error:

```
Jul 11, 2018 7:28:14 PM org.apache.jasper.compiler.Compiler generateClass
SEVERE: Error compiling file: /Users/tnguyen14/github/plantuml/plantuml-server/target/tmp/jsp/org/apache/jsp/error_jsp.java
2018-07-11 19:28:14.226:WARN:oejs.ErrorPageErrorHandler:EXCEPTION
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP||PWC6199: Generated servlet error:|Source option 5 is no longer supported. Use 6 or later.||PWC6199: Generated servlet error:|Target option 1.5 is no longer supported. Use 1.6 or later.||
        at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:126)
        at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:296)
        at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:387)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:448)
```

**Comment by arnaudroques** [comment]
I'm confused because we are targetting 1.6 in the pom file
( https://github.com/plantuml/plantuml-server/blob/master/pom.xml )
Have someone any idea about this ?

**Comment by vadimpanin** [comment]
This pull-request / diff fixes the error on current master:
https://github.com/plantuml/plantuml-server/pull/71/commits/8502a4e38caa81c02fcd9986eb9a8e7c186fac52
