### ISSUE TITLE
Docker container with tomcat and ASCII-Art output throws exception with activity beta input.

### ISSUE THREAD

**Issue by Boldie** [plantuml/plantuml-server#96]
I tried to create ASCII-Art with the docker container / tomcat. I got an exception instead of meaningful output:

```
java.lang.UnsupportedOperationException: UTXT
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:393)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:237)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:178)
	at net.sourceforge.plantuml.activitydiagram3.ActivityDiagram3.exportDiagramInternal(ActivityDiagram3.java:219)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:248)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.servlet.DiagramResponse.sendDiagram(DiagramResponse.java:105)
	at net.sourceforge.plantuml.servlet.UmlDiagramService.doDiagramResponse(UmlDiagramService.java:93)
	at net.sourceforge.plantuml.servlet.UmlDiagramService.doGet(UmlDiagramService.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)


An error has occured : java.lang.UnsupportedOperationException: UTXT
Made on Earth by humans
 
Diagram size: 23 lines / 519 characters.
 
PlantUML (1.2019.04) cannot parse result from dot/GraphViz.
 
Please go to http://plantuml.com/graphviz-dot to check your GraphViz version.
```

Input was:
```
@startuml
start
if (GGGGHH) then (yes)
   #FFFF33:Beeper;
endif
stop
@enduml
```

**Comment by Boldie** [comment]
Recently found out, the official server also will throw the same exception, so it seems to be a Bug related with the new activity syntax and Plantuml in general.

**Comment by arnaudroques** [comment]
The real issue is that export to ascii-art is not implemented for activity diagram yet.
This would need some important work to make it work.

**Comment by Boldie** [comment]
I found this out too :) Maybe there shall be a warning or something instead of an exception where nobody knows what went wrong.
